from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    Image
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from datetime import datetime
import os


def create_pdf(
    filename,
    prediction,
    confidence,
    image_size,
    resolution,
    prediction_time,
    image_path
):

    pdf_name = "prediction_report.pdf"

    doc = SimpleDocTemplate(pdf_name)

    styles = getSampleStyleSheet()

    elements = []

    # ---------- Title ----------

    title = Paragraph(
        "<font color='darkblue'><b>AI Image Recognition Report</b></font>",
        styles["Title"]
    )

    elements.append(title)
    elements.append(Spacer(1, 20))

    # ---------- Uploaded Image ----------

    if os.path.exists(image_path):

        img = Image(image_path)

        img.drawWidth = 3 * inch
        img.drawHeight = 3 * inch

        elements.append(img)
        elements.append(Spacer(1, 20))

    # ---------- Table ----------

    data = [

        ["Image Name", filename],

        ["Prediction", prediction],

        ["Confidence", "{:.2f} %".format(float(confidence))],

        ["Image Size", f"{image_size} KB"],

        ["Resolution", resolution],

        ["Prediction Time", f"{prediction_time} sec"],

        ["Generated On",
         datetime.now().strftime("%d %B %Y %I:%M %p")]

    ]

    table = Table(data, colWidths=[160, 250])

    table.setStyle(TableStyle([

        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#4F46E5")),

        ("TEXTCOLOR", (0,0), (0,-1), colors.white),

        ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold"),

        ("GRID", (0,0), (-1,-1), 1, colors.grey),

        ("BACKGROUND", (1,0), (1,-1), colors.whitesmoke),

        ("BOTTOMPADDING", (0,0), (-1,-1), 10),

        ("TOPPADDING", (0,0), (-1,-1), 10),

        ("VALIGN", (0,0), (-1,-1), "MIDDLE")

    ]))

    elements.append(table)

    elements.append(Spacer(1, 30))

    footer = Paragraph(
        "<font color='grey'>Generated by AI Image Recognition System</font>",
        styles["Italic"]
    )

    elements.append(footer)

    doc.build(elements)

    return pdf_name